/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.loginUser;
import Vista.*;
import Vista.MiInformacion;
import Vista.Reportes;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import Vista.Tablero1;
import Vista.Tablero1;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ar466
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private loginUser log;
    private String jugador1;
    private String jugador2;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
//        try {
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (Exception ex) {
//            ex.printStackTrace();
//        }
        initComponents();
        log = new loginUser();
        jugador1 = log.obtenerUsuarioLogueado();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        btnJugar = new javax.swing.JToggleButton();
        miCuentabtn = new javax.swing.JToggleButton();
        reportesbtn = new javax.swing.JToggleButton();
        btnlogout = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        btnJugar.setBackground(new java.awt.Color(119, 134, 165));
        btnJugar.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        btnJugar.setText("Stratego - Marvel Heroes!");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setFocusPainted(false);
        btnJugar.setFocusable(false);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        miCuentabtn.setBackground(new java.awt.Color(40, 46, 58));
        miCuentabtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        miCuentabtn.setText("Mi Perfil");
        miCuentabtn.setBorderPainted(false);
        miCuentabtn.setContentAreaFilled(false);
        miCuentabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        miCuentabtn.setFocusPainted(false);
        miCuentabtn.setFocusable(false);
        miCuentabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCuentabtnActionPerformed(evt);
            }
        });

        reportesbtn.setBackground(new java.awt.Color(40, 46, 58));
        reportesbtn.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        reportesbtn.setText("Universo Marvel");
        reportesbtn.setBorder(null);
        reportesbtn.setBorderPainted(false);
        reportesbtn.setContentAreaFilled(false);
        reportesbtn.setFocusPainted(false);
        reportesbtn.setFocusable(false);
        reportesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesbtnActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(40, 46, 58));
        btnlogout.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        btnlogout.setText("Cerrar Sesion");
        btnlogout.setBorderPainted(false);
        btnlogout.setContentAreaFilled(false);
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnlogout.setFocusPainted(false);
        btnlogout.setFocusable(false);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar)
                    .addComponent(reportesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(miCuentabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(reportesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres cerrar sesión?", "Confirmación de cierre de sesión", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            MenuInicio m = new MenuInicio();
            m.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void reportesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesbtnActionPerformed
        /// Abre la ventana de Reportes
        Reportes r = new Reportes();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportesbtnActionPerformed

    private void miCuentabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCuentabtnActionPerformed
        MiInformacion m = new MiInformacion();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miCuentabtnActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        String[] oponentes = log.obtenerOponentesDisponibles();
        if (oponentes.length == 0) {
            JOptionPane.showMessageDialog(this, "No hay oponentes disponibles, intente más tarde");
        } else {
            String oponenteSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione su oponente:", "Seleccionar Oponente", JOptionPane.QUESTION_MESSAGE, null, oponentes, oponentes[0]);
            if (oponenteSeleccionado != null) {
                seleccionarBando(oponenteSeleccionado);
            }
        }


    }//GEN-LAST:event_btnJugarActionPerformed
    private void seleccionarBando(String oponenteSeleccionado) {
        String[] opciones = {"Heroes", "Villanos"};
        String bandoSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione su bando:", "Seleccionar Bando", JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        
        if (bandoSeleccionado != null) {
            iniciarJuego(oponenteSeleccionado, bandoSeleccionado);
        }
    }

    private void iniciarJuego(String jugador2, String bando) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        Tablero1 tablero = new Tablero1(jugador2, bando);
        tablero.setVisible(true);
        this.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnJugar;
    private javax.swing.JToggleButton btnlogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton miCuentabtn;
    private javax.swing.JToggleButton reportesbtn;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/resources/MenuIniciall.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
}
