/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.loginUser;
import Vista.Reportes;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Dennisse
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        actualizarRanking();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        posicionLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        puntosLabel = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        posicionInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        usernameInfo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        puntosInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        posicionLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        posicionLabel.setText("Posición");

        usernameLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        usernameLabel.setText("Username");

        puntosLabel.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        puntosLabel.setText("Puntos");

        regresarBtn.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        regresarBtn.setText("Regresar");
        regresarBtn.setBorderPainted(false);
        regresarBtn.setContentAreaFilled(false);
        regresarBtn.setFocusPainted(false);
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        posicionInfo.setEditable(false);
        posicionInfo.setColumns(1);
        posicionInfo.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        posicionInfo.setRows(5);
        jScrollPane1.setViewportView(posicionInfo);

        usernameInfo.setEditable(false);
        usernameInfo.setColumns(1);
        usernameInfo.setRows(5);
        jScrollPane2.setViewportView(usernameInfo);

        puntosInfo.setEditable(false);
        puntosInfo.setColumns(1);
        puntosInfo.setRows(5);
        jScrollPane3.setViewportView(puntosInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(regresarBtn)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(posicionLabel)
                                .addGap(64, 64, 64))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usernameLabel)
                                .addGap(63, 63, 63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(puntosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))
                        .addGap(84, 84, 84))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(puntosLabel)
                    .addComponent(posicionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresarBtn)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        Reportes reportes = new Reportes();
        reportes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarBtnActionPerformed
    private void actualizarRanking() {
        // Crear un arreglo para almacenar los jugadores activos
        Jugador[] jugadores = new Jugador[loginUser.count];
        int jugadoresActivosCount = 0;

        // Llenar el arreglo con los jugadores activos
        for (int i = 0; i < loginUser.count; i++) {
            if (loginUser.activos[i]) {
                jugadores[jugadoresActivosCount++] = new Jugador(loginUser.usuarios[i], loginUser.puntosArr[i]);
            }
        }

        // Ordenar el arreglo por puntos en orden descendente
        for (int i = 0; i < jugadoresActivosCount - 1; i++) {
            for (int j = i + 1; j < jugadoresActivosCount; j++) {
                if (jugadores[i].getPuntos() < jugadores[j].getPuntos()) {
                    Jugador temp = jugadores[i];
                    jugadores[i] = jugadores[j];
                    jugadores[j] = temp;
                }
            }
        }

        // Construir las cadenas de texto del ranking
        StringBuilder posicionesBuilder = new StringBuilder();
        StringBuilder usernamesBuilder = new StringBuilder();
        StringBuilder puntosBuilder = new StringBuilder();

        for (int i = 0; i < jugadoresActivosCount; i++) {
            Jugador jugador = jugadores[i];
            posicionesBuilder.append(i + 1).append("\n");
            usernamesBuilder.append(jugador.getUsername()).append("\n");
            puntosBuilder.append(jugador.getPuntos()).append("\n");
        }

        // Mostrar el ranking en los JTextArea
        posicionInfo.setText(posicionesBuilder.toString());
        usernameInfo.setText(usernamesBuilder.toString());
        puntosInfo.setText(puntosBuilder.toString());
    }

// Clase Jugador
    private class Jugador {

        private String username;
        private int puntos;

        public Jugador(String username, int puntos) {
            this.username = username;
            this.puntos = puntos;
        }

        public String getUsername() {
            return username;
        }

        public int getPuntos() {
            return puntos;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea posicionInfo;
    private javax.swing.JLabel posicionLabel;
    private javax.swing.JTextArea puntosInfo;
    private javax.swing.JLabel puntosLabel;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JTextArea usernameInfo;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/resources/ranking.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }

}
